name    'alkivi-openerp'
version '0.1.1'
source 'https://github.com/alkivi-sas/puppet-openerp'
author 'alkivi'
license 'LGPLv3'
summary 'Controls installation and configuration of an OpenERP server'
project_page 'https://github.com/alkivi-sas/puppet-openerp'
dependency 'puppetlabs/stdlib', '>=3.0.0'
